<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <button onclick="fonksiyon()">Click Me</button>
    <script>
        //değer almadan  çalışan fonksiyon değer vermiyoruz
        function fonksiyon(){}
        //değer almadan çalışan fonksiyon
        function fonksiyon1(){
            alert("Merhaba");
        }
        //fonksiyon1
        //değer alan fonksiyon alınan değerleri toplar
        function fonksiyon2(a , b){
            alert(a + b);
        }
        //değer alan fonksiyon alınan değerleri toplar ve döndürür
        function fonksiyon3(a , b){
            return a + b;
        }
        //alert(fonksiyon3(2 ,2));
        //dışardan değer alan ve içerde bizim belirlediğimiz değeride veren fonksiyon
        function fonksiyon4(isim){
            return "merhaba" + isim;
        }
        alert(fonksiyon4("Ahmet"));
    </script>
</body>
</html>








<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //array kullanımı
        var array=["Ahmet","Mehmet","Ali","Veli"];//array tanımlama
        let array2=["Ahmet","Mehmet","Ali","Veli"];//array tanımlama
        array.push("hasan");//array sonuna eleman ekleme
        array.unshift("Hüseyin");//array başına eleman ekleme
        array.pop();//array sonundan eleman silme
        array.shift();//array başından eleman silme
        //array içindeki elemanları yazdırma
        for (let i = 0; i < array.length;i++ ){
            console.log(array[i]);
        }
        var sayilar = [1,2,3,4,5,6,7,8,9,10];
        //sayılar içindeki elemanları filtreleme
        var yenisayilar = sayilar.filter(function (sayi){
            return sayi  >5;
        });
        console.log(yenisayilar);
        //array  map kullanımı
        var sayilar2 = [1,2,3,4,5,6,7,8,9,10];
        var yenisayilar2 = sayilar2.map(function(sayi){
            return sayi * 2;
        });
        console.log(yenisayilar2);
    </script>
</body>
</html>










<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <!--
    main div
    navbar->logo, navlinks->search
    sidebar->categories, tags
    content->posts
    footer->social media links
    -->
    <div class="container">
      <header class="header">
        <div class="col2">
          <img src="logo.png" alt="logo" class="logo" />
        </div>
        <div class="col6">
          <nav class="nav">
            <ul class="nav__list">
              <li class="nav__item">
                <a href="#" class="nav__link">Anasayfa</a>
              </li>
              <li class="nav__item">
                <a href="#" class="nav__link">Hakkımızda</a>
              </li>
              <li class="nav__item">
                <a href="#" class="nav__link">Hizmetlerimiz</a>
              </li>
              <li class="nav__item">
                <a href="#" class="nav__link">İletişim</a>
              </li>
            </ul>
          </nav>
        </div>
        <!--
        <div class="col4">
          <input type="text" class="search" placeholder="Search" />
        </div>
        -->
      </header>
      <div class="main">
        <!-- banner-->
        <div class="col12 banner">
          <img
            src="https://picsum.photos/1200/300?grayscale"
            alt="banner"
            class="banner"
          />
        </div>
        <div class="sidebar">
          <div class="categories">
            <h2 class="categories__title">Kategoriler</h2>
            <ul class="categories__list">
              <li class="categories__item">
                <a href="#" class="categories__link">Kategori 1</a>
              </li>
              <li class="categories__item">
                <a href="#" class="categories__link">Kategori 2</a>
              </li>
              <li class="categories__item">
                <a href="#" class="categories__link">Kategori 3</a>
              </li>
              <li class="categories__item">
                <a href="#" class="categories__link">Kategori 4</a>
              </li>
              <li class="categories__item">
                <a href="#" class="categories__link">Kategori 5</a>
              </li>
            </ul>
          </div>
          <div class="tags">
            <h2 class="tags__title">Etiketler</h2>
            <ul class="tags_list">
              <li class="tags_item">Mazagin</li>
              <li class="tags_item">RTE</li>
              <li class="tags_item">Serdar Ortaç</li>
              <li class="tags_item">Kodusta</li>
              <li class="tags_item">Kodluyoruz</li>
            </ul>
          </div>
        </div>
        <div class="content">
          <div class="col4">
            <div class="post">
              <img
                src="https://picsum.photos/200/300?grayscale"
                alt="post"
                class="post__img"
              />
              <h3 class="post__title">Flaş Haber</h3>
              <p class="post__content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Perferendis quo pariatur, eveniet error sed repellendus
                aspernatur molestias dicta praesentium alias. Recusandae
                reprehenderit deleniti nulla ratione voluptatem laudantium omnis
                optio labore?
              </p>
              <!-- paylaş button-->
              <a href="#" class="share_href">Paylaş</a>
              <!-- yorum yap button-->
              <button type="button" class="comment_button">Yorum Yap</button>
            </div>
          </div>
          <div class="col4">
            <div class="post">
              <img
                src="https://picsum.photos/200/300?grayscale"
                alt="post"
                class="post__img"
              />
              <h3 class="post__title">Flaş Haber</h3>
              <p class="post__content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Perferendis quo pariatur, eveniet error sed repellendus
                aspernatur molestias dicta praesentium alias. Recusandae
                reprehenderit deleniti nulla ratione voluptatem laudantium omnis
                optio labore?
              </p>
              <!-- paylaş button-->
              <a href="#" class="share_href">Paylaş</a>
              <!-- yorum yap button-->
              <button type="button" class="comment_button">Yorum Yap</button>
            </div>
          </div>
          <div class="col4">
            <div class="post">
              <img
                src="https://picsum.photos/200/300?grayscale"
                alt="post"
                class="post__img"
              />
              <h3 class="post__title">Flaş Haber</h3>
              <p class="post__content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Perferendis quo pariatur, eveniet error sed repellendus
                aspernatur molestias dicta praesentium alias. Recusandae
                reprehenderit deleniti nulla ratione voluptatem laudantium omnis
                optio labore?
              </p>
              <!-- paylaş button-->
              <a href="#" class="share_href">Paylaş</a>
              <!-- yorum yap button-->
              <button type="button" class="comment_button">Yorum Yap</button>
            </div>
          </div>
          <div class="col4">
            <div class="post">
              <img
                src="https://picsum.photos/200/300?grayscale"
                alt="post"
                class="post__img"
              />
              <h3 class="post__title">Flaş Haber</h3>
              <p class="post__content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Perferendis quo pariatur, eveniet error sed repellendus
                aspernatur molestias dicta praesentium alias. Recusandae
                reprehenderit deleniti nulla ratione voluptatem laudantium omnis
                optio labore?
              </p>
              <!-- paylaş button-->
              <a href="#" class="share_href">Paylaş</a>
              <!-- yorum yap button-->
              <button type="button" class="comment_button">Yorum Yap</button>
            </div>
          </div>
          <div class="col4">
            <div class="post">
              <img
                src="https://picsum.photos/200/300?grayscale"
                alt="post"
                class="post__img"
              />
              <h3 class="post__title">Flaş Haber</h3>
              <p class="post__content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Perferendis quo pariatur, eveniet error sed repellendus
                aspernatur molestias dicta praesentium alias. Recusandae
                reprehenderit deleniti nulla ratione voluptatem laudantium omnis
                optio labore?
              </p>
              <!-- paylaş button-->
              <a href="#" class="share_href">Paylaş</a>
              <!-- yorum yap button-->
              <button type="button" class="comment_button">Yorum Yap</button>
            </div>
          </div>
          <div class="col4">
            <div class="post">
              <img
                src="https://picsum.photos/200/300?grayscale"
                alt="post"
                class="post__img"
              />
              <h3 class="post__title">Flaş Haber</h3>
              <p class="post__content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Perferendis quo pariatur, eveniet error sed repellendus
                aspernatur molestias dicta praesentium alias. Recusandae
                reprehenderit deleniti nulla ratione voluptatem laudantium omnis
                optio labore?
              </p>
              <!-- paylaş button-->
              <a href="#" class="share_href">Paylaş</a>
              <!-- yorum yap button-->
              <button type="button" class="comment_button">Yorum Yap</button>
            </div>
          </div>
          <div id="none" style="display: none">
            <div class="col4">
              <div class="post">
                <img
                  src="https://picsum.photos/200/300?grayscale"
                  alt="post"
                  class="post__img"
                />
                <h3 class="post__title">Flaş Haber</h3>
                <p class="post__content">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Perferendis quo pariatur, eveniet error sed repellendus
                  aspernatur molestias dicta praesentium alias. Recusandae
                  reprehenderit deleniti nulla ratione voluptatem laudantium
                  omnis optio labore?
                </p>
                <!-- paylaş button-->
                <a href="#" class="share_href">Paylaş</a>
                <!-- yorum yap button-->
                <button type="button" class="comment_button">Yorum Yap</button>
              </div>
            </div>
            <div class="col4">
              <div class="post">
                <img
                  src="https://picsum.photos/200/300?grayscale"
                  alt="post"
                  class="post__img"
                />
                <h3 class="post__title">Flaş Haber</h3>
                <p class="post__content">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Perferendis quo pariatur, eveniet error sed repellendus
                  aspernatur molestias dicta praesentium alias. Recusandae
                  reprehenderit deleniti nulla ratione voluptatem laudantium
                  omnis optio labore?
                </p>
                <!-- paylaş button-->
                <a href="#" class="share_href">Paylaş</a>
                <!-- yorum yap button-->
                <button type="button" class="comment_button">Yorum Yap</button>
              </div>
            </div>
            <div class="col4">
              <div class="post">
                <img
                  src="https://picsum.photos/200/300?grayscale"
                  alt="post"
                  class="post__img"
                />
                <h3 class="post__title">Flaş Haber</h3>
                <p class="post__content">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Perferendis quo pariatur, eveniet error sed repellendus
                  aspernatur molestias dicta praesentium alias. Recusandae
                  reprehenderit deleniti nulla ratione voluptatem laudantium
                  omnis optio labore?
                </p>
                <!-- paylaş button-->
                <a href="#" class="share_href">Paylaş</a>
                <a
                  href="https://www.linkedin.com/shareArticle?url=file:///Users/selahaddinciftci/Desktop/ders/index3.html#&title=Flaş Haber"
                  class="linkedin"
                  target="_blank"
                  >LinkedIn'de Paylaş</a
                >
                <!-- yorum yap button-->
                <button type="button" class="comment_button">Yorum Yap</button>
              </div>
            </div>
          </div>
          <button
            type="button"
            class="loadmore"
            onclick="loadMore1()"
            style="display: none"
            id="load1"
          >
            Daha Az Göster
          </button>
          <button type="button" class="loadmore" onclick="loadMore()" id="load">
            Daha Fazla Göster
          </button>
        </div>
      </div>
      <footer class="footer">
        <ul class="social__list">
          <li class="social__item">
            <a href="#" class="social__link">Bahance</a>
          </li>
          <li class="social__item">
            <a href="#" class="social__link">Github</a>
          </li>
          <li class="social__item">
            <a href="#" class="social__link">Stackoverflow</a>
          </li>
          <li class="social__item">
            <a href="#" class="social__link">Linkedin</a>
          </li>
        </ul>
      </footer>
    </div>
    <script>
      function loadMore() {
        document.getElementById("none").style.display = "block";
        document.getElementById("load").style.display = "none";
        document.getElementById("load1").style.display = "block";
      }
      function loadMore1() {
        document.getElementById("none").style.display = "none";
        document.getElementById("load").style.display = "block";
        document.getElementById("load1").style.display = "none";
      }
    </script>
  </body>
</html>
























